
import React from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Footer from "@/components/layout-components/footer/Footer";
import Navbar from "@/components/layout-components/header/Navbar";

import { UIProvider } from "@/context/ui/UIProvider";

import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function ProductLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <div>
        <UIProvider>
          <Navbar />
           {children}
          <Footer />
        </UIProvider>
    </div>
  );
}
