
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout-components/header/Navbar";
import 'bootstrap/dist/css/bootstrap.min.css';
import Banner from "@/components/layout-components/banner/Banner";
import Contact from "@/components/layout-components/contact/Contact";
import Footer from "@/components/layout-components/footer/Footer";
import { UIProvider } from "@/context/ui/UIProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <UIProvider>
          <Navbar />
          {children}
          <Footer />
        </UIProvider>
      </body>
    </html>
  );
}
