import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "Tesla | Shop",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    );
}
